In [16]:
import numpy as np
import sys ,time

In [17]:
arr = np.array([23,41,15,65,80])

In [18]:
arr

array([23, 41, 15, 65, 80])

In [19]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
x + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
y = np.arange(1,11,3)

In [24]:
y

array([ 1,  4,  7, 10])

In [25]:
np.arange(1,15,2,dtype = 'float32')

array([ 1.,  3.,  5.,  7.,  9., 11., 13.], dtype=float32)

In [26]:
np.arange(1,15,2,dtype = 'float8')

TypeError: data type 'float8' not understood

In [ ]:
list_1 = [2,3,6,5]
x = np.array([4,5,6,7])

In [27]:
sys.getsizeof([])

56

In [28]:
y = np.array([])

In [30]:
sys.getsizeof(np.array([]))

112

In [31]:
sys.getsizeof([1,2])

72

In [32]:
sys.getsizeof(np.array([1,2]))

120

In [33]:
sys.getsizeof(np.array([1,2,3,4,6,7,8,9,5,6,2,4]))

160

In [34]:
sys.getsizeof([1,2,3,4,6,7,8,9,5,6,2,4])

152

In [41]:
list_1 = list(range(10000000))
list_2 = list(range(10000000))
lists_3 = []
start = time.time()


for i in range(len(list_1)):
    lists_3.append(list_1[i] + list_2[i])
    
end = time.time()

total = end - start

print("total time taken is:",total)

total time taken is: 2.539013624191284


In [42]:
arr_1 = np.array(list_1)
arr_2 = np.array(list_2)

start = time.time()

arr_3 = arr_1 + arr_2

end = time.time()
total = end - start
print("total time taken by array is:",total)

total time taken by array is: 0.01772165298461914


In [45]:
np.linspace(2,20,num = 11,retstep = True)

(array([ 2. ,  3.8,  5.6,  7.4,  9.2, 11. , 12.8, 14.6, 16.4, 18.2, 20. ]),
 1.8)

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [49]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.random.randn()

array([ 1.24686254,  1.73125248, -0.83114311,  1.19402699,  0.83890135])

In [52]:
np.random.randint(1,100)

50

In [53]:
np.random.randint(1,100,10)

array([87, 14, 99, 67, 31, 92, 56, 31, 53, 77])

In [56]:
x = np.random.randint(1,100,15)

In [62]:
y = np.random.randint(1,100,[4,5])

In [63]:
y

array([[ 4, 64, 33, 51,  1],
       [98, 84, 67, 50, 36],
       [47, 39, 34, 61,  9],
       [ 2, 39, 25, 72, 50]])

In [57]:
x

array([43, 17, 56, 13, 54, 17, 90,  2, 63, 72, 16, 35, 19,  2, 77])

In [58]:
x[-1]

77

In [59]:
x[5]

17

In [60]:
x[2:9]

array([56, 13, 54, 17, 90,  2, 63])

In [65]:
y

array([[ 4, 64, 33, 51,  1],
       [98, 84, 67, 50, 36],
       [47, 39, 34, 61,  9],
       [ 2, 39, 25, 72, 50]])

In [68]:
y[1:5:2,1:5:2]

array([[84, 50],
       [39, 72]])